### ISSUE TITLE
m.getInStrOffset() should be m.getStrOffset() at Writing WASM Memory plnkr

### ISSUE THREAD

**Issue by guest271314** [guybedford/wasm-intro#2]
`m.getInStrOffset()` is not a function at https://embed.plnkr.co/SnBwi3sUmcFQhh0FPIsR?autoCloseSidebar=true&show=program.c,index.html. Should be `m.getStrOffset()`. 

What is the expected result of `m.toLowerCase()` (`console.log(new TextDecoder().decode(new Uint8Array(mem.buffer)).toLowerCase())`)?

**Comment by guybedford** [comment]
Thanks for posting - it looks like it's using the wrong Wasm file URL from example 4 instead of the current example which is the Wasm binary at https://cdn.rawgit.com/guybedford/wasm-intro/dc93a5f3/5-writing-wasm-memory/program.wasm. If you update the URL in the plunk to that one it should then work correctly!

**Comment by guybedford** [comment]
I've just updated the Plunkr so it should be working now!
